ratings = {"Trung": 1500, "Michael": 1500, "Asier": 1500, "Christian": 1500}
matches = [
    [["Asier"], ["Trung"]],
    [["Asier"], ["Michael"]],
    [["Michael"], ["Asier"]],
    [["Michael"], ["Asier"]],
    [["Michael"], ["Asier"]],
    [["Trung"], ["Michael"]],
    [["Trung"], ["Michael"]],
    [["Trung"], ["Michael"]],
    [["Trung"], ["Michael"]],
    [["Trung"], ["Asier"]],
    [["Asier"], ["Trung"]],
    [["Asier"], ["Trung"]],
    [["Michael"], ["Asier"]],
    [["Michael"], ["Asier"]],
    [["Michael"], ["Asier"]],
    [["Asier"], ["Michael"]],
    [["Asier"], ["Michael"]],
    [["Asier"], ["Michael"]],
    [["Trung"], ["Michael"]],
    [["Asier"], ["Trung"]],
]
